# Use Nginx as a base image
FROM nginx:alpine

# Copy frontend files to Nginx's default directory
COPY . /usr/share/nginx/html

# Expose HTTP port
EXPOSE 80

# Run Nginx
CMD ["nginx", "-g", "daemon off;"]
