version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8765:8765"
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
