# Use Python base image
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy backend files
COPY . /app

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose WebSocket port
EXPOSE 8765

# Run the server
CMD ["python", "server1.py"]
